Repository FoundationDB/fdb-record-layer, pull requests merged in 2025-06, with the labels that each got.

#3342 Add API for repairing a missing store header
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreRepairHeaderTest.java
Labels: enhancement

#3382 (non)-partitioning properties for `Reference`s
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ExpressionPartition.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ExpressionPartitions.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ExpressionPropertiesMap.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/FindExpressionVisitor.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/LinkedIdentityMap.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PlanPartition.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PlanPartitions.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PlanPropertiesMap.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PlannerStage.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Reference.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/matching/structure/ExpressionsPartitionMatchers.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/DistinctRecordsProperty.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/OrderingProperty.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/PrimaryKeyProperty.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/SelectCountProperty.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/StoredRecordProperty.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/FinalizeExpressionsRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementDeleteRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementDistinctRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementDistinctUnionRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementInJoinRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementInUnionRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementIntersectionRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementStreamingAggregationRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementTypeFilterRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementUniqueRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementUpdateRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/RemoveSortRule.java
Labels: enhancement

#3396 Allow version repair to operate while the store is locked
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBTypedRecordStore.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/recordrepair/RecordVersionValidator.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RecordsUpdateLockTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/recordrepair/RecordValidateAndRepairTest.java
Labels: bug fix

#3399 Bring in 4.3.3.1 release notes
  docs/sphinx/source/ReleaseNotes.md
Labels: documentation

#3403 `QueryPredicate` constant folding
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/matching/structure/QueryPredicateMatchers.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/matching/structure/ValueMatchers.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/PredicateWithValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/PredicateWithValueAndRanges.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/RangeConstraints.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/simplification/ConstantFoldingPredicateWithRangesRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/simplification/ConstantFoldingRuleSet.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/simplification/ConstantFoldingValuePredicateRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/simplification/ConstantPredicateFoldingUtil.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/simplification/DefaultQueryPredicateRuleSet.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/simplification/QueryPredicateWithCnfRuleSet.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/simplification/QueryPredicateWithDnfRuleSet.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/simplification/ValuePredicateSimplificationRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/PredicateToLogicalUnionRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/Type.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/ConstantObjectValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/LiteralValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/Value.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/DereferenceConstantObjectValueRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/DereferenceConstantObjectValueRuleSet.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/FoldingValueSimplificationRuleSet.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/ConstantFoldingTestUtils.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/predicates/ConstantFoldingTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/predicates/QueryPredicateTest.java
Labels: enhancement

#3411 Planner rewrite rule for simplifying `SelectExpression` predicates
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/matching/structure/MultiMatcher.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/simplification/ConstantFoldingMultiConstraintPredicateRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/simplification/ConstantFoldingRuleSet.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/simplification/ConstantPredicateFoldingUtil.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/QueryPredicateSimplificationRule.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/RuleTestHelper.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/rules/QueryPredicateSimplificationRuleTest.java
Labels: enhancement, planner

#3413 Introduce value-specific plan cache constraints
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/EvaluatesToValue.java
  fdb-record-layer-core/src/main/proto/record_query_plan.proto
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/ConstantFoldingTestUtils.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/values/EvaluatesToValueTest.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/MutablePlanGenerationContext.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/QueryPlan.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/cache/ConstraintValidityTests.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/cache/RelationalPlanCacheTests.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/cache/ValueSpecificConstraintTests.java
Labels: enhancement

#3416 Allow MaintainYamlTestConfig with quickTest
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlTestExtension.java
Labels: testing improvement

#3423 Address case where `markIndexReadable` could ignore `allowUniquePending` parameter
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
Labels: bug fix

#3427 Scoring and costing query predicates
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ExpressionPropertiesMap.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/RewritingCostModel.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/TreeLike.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/PredicateComplexityProperty.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/values/TreeDiameterTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/values/ValueHeightTest.java
Labels: enhancement, planner

#3426 Address nullability of null-on-empty quantifiers and nested fields
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Quantifier.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/Type.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/FieldValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryDefaultOnEmptyPlan.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSimpleQueryGraphTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/ConstantFoldingTestUtils.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/predicates/ConstantFoldingTest.java
  yaml-tests/src/main/proto/nested_nulls_proto_test.proto
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/nested-with-nulls-proto.metrics.binpb
  yaml-tests/src/test/resources/nested-with-nulls-proto.metrics.yaml
  yaml-tests/src/test/resources/nested-with-nulls-proto.yamsql
  yaml-tests/src/test/resources/nested-with-nulls.metrics.binpb
  yaml-tests/src/test/resources/nested-with-nulls.metrics.yaml
  yaml-tests/src/test/resources/nested-with-nulls.yamsql
Labels: bug fix

#3440 Separate out Lucene tests so they run separately in PRB
  .github/workflows/pull_request.yml
Labels: build improvement

#3442 Run expensive `Traversal` verification sanity check less often
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/CascadesPlanner.java
Labels: testing improvement

#3448 `OfTypeValue` distinguishes `long` and `int`
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/OfTypeValue.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/OfTypeValueTest.java
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/literal-tests.metrics.binpb
  yaml-tests/src/test/resources/literal-tests.metrics.yaml
  yaml-tests/src/test/resources/literal-tests.yamsql
Labels: bug fix

#3450 Update code version before running tests in release build
  .github/workflows/release.yml
Labels: build improvement

#3451 add placeholders in all appropriate select expressions
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AggregateIndexExpansionVisitor.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/KeyExpressionExpansionVisitor.java
Labels: bug fix
