Repository FoundationDB/fdb-record-layer, pull requests merged in 2025-05, with the labels that each got.

#3339 Remove jfrog from repository list
  build.gradle
Labels: build improvement

#3345 Remove 4.2.7.0 release notes as build was never published
  docs/sphinx/source/ReleaseNotes.md
Labels: documentation

#3336 ParameterizedTest utilities
  fdb-extensions/src/test/java/com/apple/foundationdb/async/MoreAsyncUtilTest.java
  fdb-extensions/src/test/java/com/apple/test/BooleanArgumentsProvider.java
  fdb-extensions/src/test/java/com/apple/test/BooleanSource.java
  fdb-extensions/src/test/java/com/apple/test/ParameterizedTestUtils.java
  fdb-extensions/src/test/java/com/apple/test/ParameterizedTestUtilsTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/APIVersionTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreUniqueIndexTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/runners/TransactionalRunnerTest.java
Labels: testing improvement

#3334 Add RecordCountKey State
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FormatVersion.java
  fdb-record-layer-core/src/main/proto/record_metadata.proto
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreCountRecordsTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FormatVersionTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/recordrepair/RecordValidationTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/recordrepair/ScanRecordKeysTest.java
  gradle.properties
Labels: enhancement

#3347 Create FutureManagerRunner and convert FDBDatabaseRunnerImpl to use it.
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunnerImpl.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/runners/FutureAutoClose.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/runners/TransactionalRunner.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/runners/FutureAutoCloseTest.java
Labels: enhancement

#3324 New planner rule added to push predicates down in the query representation
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/CascadesRuleCall.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ExploratoryMemoizer.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Reference.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/matching/structure/QuantifierMatchers.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/matching/structure/RecordQueryPlanMatchers.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/matching/structure/ReferenceMatchers.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/PredicateWithValueAndRanges.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/QueryPredicate.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/ValuePredicate.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/PredicatePushDownRule.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBQueryGraphTestHelpers.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBSimpleQueryGraphTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/MemoExpressionTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/rules/PredicatePushDownRuleTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/rules/RuleTestHelper.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/rules/TestRuleExecution.java
Labels: enhancement

#3358 Fix deprecated Gradle syntax and configuration features
  build.gradle
  examples/examples.gradle
  fdb-relational-api/fdb-relational-api.gradle
  fdb-relational-cli/fdb-relational-cli.gradle
  fdb-relational-jdbc/fdb-relational-jdbc.gradle
  fdb-relational-server/fdb-relational-server.gradle
  gradle/testing.gradle
  yaml-tests/yaml-tests.gradle
Labels: build improvement

#3365 Don't memoize correlation sets in planner objects
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Quantifier.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Reference.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ScanWithFetchMatchCandidate.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/PushFilterThroughFetchRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/IndexedValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/RecordTypeValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryAggregateIndexPlan.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBNestedRepeatedQueryTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/ValueComputationTest.java
  yaml-tests/src/test/resources/aggregate-index-tests.metrics.binpb
  yaml-tests/src/test/resources/aggregate-index-tests.metrics.yaml
  yaml-tests/src/test/resources/bitmap-aggregate-index.metrics.binpb
  yaml-tests/src/test/resources/bitmap-aggregate-index.metrics.yaml
  yaml-tests/src/test/resources/cte.metrics.binpb
  yaml-tests/src/test/resources/cte.metrics.yaml
  yaml-tests/src/test/resources/recursive-cte.metrics.binpb
  yaml-tests/src/test/resources/recursive-cte.metrics.yaml
  yaml-tests/src/test/resources/standard-tests.metrics.binpb
  yaml-tests/src/test/resources/standard-tests.metrics.yaml
  yaml-tests/src/test/resources/subquery-tests.metrics.binpb
  yaml-tests/src/test/resources/subquery-tests.metrics.yaml
Labels: bug fix

#3371 Reenable memoization of correlated-to sets
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Quantifier.java
Labels: performance

#3333 Planner now uses correct calculation for ordering of aggregate scans over permuted min/max indexes
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/AggregateIndexMatchCandidate.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBPermutedMinMaxQueryTest.java
  yaml-tests/src/test/resources/aggregate-index-tests.metrics.binpb
  yaml-tests/src/test/resources/aggregate-index-tests.metrics.yaml
  yaml-tests/src/test/resources/aggregate-index-tests.yamsql
Labels: bug fix

#3369 Add a test to verify setOption LOG_QUERY works per statement
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/QueryLoggingTest.java
Labels: testing improvement
