Repository FoundationDB/fdb-record-layer, pull requests merged in 2025-02, with the labels that each got.

#3112 Resolves #3172: Fix continuation bug in StreamAggregation plan
  docs/ReleaseNotes.md
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/aggregate/AggregateCursor.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBStreamAggregationTest.java
Labels: bug fix

#3168 `RecordQueryPlanComplexityException` now includes only a shortened plan string as a log message key
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanComplexityException.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/RecordQueryPlanner.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/CascadesPlanner.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreQueryTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/PlanComplexityExceededTest.java
Labels: enhancement

#3164 Cache FDB packages during the build and avoid checking them in
  .gitignore
  actions/setup-fdb/action.yml
Labels: build improvement

#3181 Enforce all PRs are labeled for Release Note generation
  .github/workflows/pr_labels.yml
  build/release-notes-config.json
Labels: build improvement

#3176 Enable a few tests where the force continuation option does not fail anymore
  yaml-tests/src/test/java/YamlIntegrationTests.java
Labels: testing improvement

#3101 Upgrade protobuf plugin from 0.8.19 to 0.9.4
  fdb-record-layer-jmh/fdb-record-layer-jmh.gradle
  fdb-relational-grpc/fdb-relational-grpc.gradle
  gradle/libs.versions.toml
  gradle/proto.gradle
Labels: dependencies

#3182 Yaml tests: Add protection against infinite continuation loops
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/QueryExecutor.java
Labels: testing improvement

#3184 Fix link to documentation in README
  README.md
Labels: documentation

#3174 Generate release notes automatically from pull requests
  .github/release.yml
  .github/workflows/patch_release.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
  actions/release-build-publish/action.yml
  build/create_release_notes.py
  docs/sphinx/source/ReleaseNotes.md
Labels: documentation, build improvement

#3189 Add version information to yaml test exceptions
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/MultiServerConnectionFactory.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/SimpleYamlConnection.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlConnection.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlConnectionFactory.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlExecutionContext.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlRunner.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/ConnectedBlock.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/SetupBlock.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/TestBlock.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/Command.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/QueryCommand.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/QueryConfig.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/QueryExecutor.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/SkippedCommand.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/ConfigWithOptions.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/EmbeddedConfig.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/JDBCInProcessConfig.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/MultiServerConfig.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/YamlTestConfig.java
  yaml-tests/src/test/java/MultiServerConnectionFactoryTest.java
  yaml-tests/src/test/java/SupportedVersionTest.java
Labels: testing improvement

#3185 Fix instability in the query planner
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/Comparisons.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/CascadesRuleCall.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/LinkedIdentityMap.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Reference.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Traversal.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/debug/Debugger.java
  fdb-record-layer-core/src/main/java/com/google/common/graph/StableDirectedMultiNetworkConnections.java
  fdb-record-layer-core/src/main/java/com/google/common/graph/StableStandardMutableNetwork.java
  fdb-record-layer-core/src/main/java/com/google/common/graph/package-info.java
  fdb-record-layer-core/src/main/proto/planner_debugger.proto
  gradle/codequality/suppressions.xml
  yaml-tests/src/test/resources/aggregate-empty-table.metrics.binpb
  yaml-tests/src/test/resources/aggregate-empty-table.metrics.yaml
  yaml-tests/src/test/resources/aggregate-index-tests-count-empty.metrics.binpb
  yaml-tests/src/test/resources/aggregate-index-tests-count-empty.metrics.yaml
  yaml-tests/src/test/resources/aggregate-index-tests-count.metrics.binpb
  yaml-tests/src/test/resources/aggregate-index-tests-count.metrics.yaml
  yaml-tests/src/test/resources/aggregate-index-tests.metrics.binpb
  yaml-tests/src/test/resources/aggregate-index-tests.metrics.yaml
  yaml-tests/src/test/resources/bitmap-aggregate-index.metrics.binpb
  yaml-tests/src/test/resources/bitmap-aggregate-index.metrics.yaml
  yaml-tests/src/test/resources/cte.metrics.binpb
  yaml-tests/src/test/resources/cte.metrics.yaml
  yaml-tests/src/test/resources/indexed-functions.metrics.binpb
  yaml-tests/src/test/resources/indexed-functions.metrics.yaml
  yaml-tests/src/test/resources/orderby.metrics.binpb
  yaml-tests/src/test/resources/orderby.metrics.yaml
  yaml-tests/src/test/resources/recursive-cte.metrics.binpb
  yaml-tests/src/test/resources/recursive-cte.metrics.yaml
  yaml-tests/src/test/resources/union-empty-tables.metrics.binpb
  yaml-tests/src/test/resources/union-empty-tables.metrics.yaml
  yaml-tests/src/test/resources/union.metrics.binpb
  yaml-tests/src/test/resources/union.metrics.yaml
  yaml-tests/src/test/resources/update-delete-returning.metrics.binpb
  yaml-tests/src/test/resources/update-delete-returning.metrics.yaml
  yaml-tests/src/test/resources/versions-tests.metrics.binpb
  yaml-tests/src/test/resources/versions-tests.metrics.yaml
Labels: bug fix

#3196 Change netty logs to INFO when running tests
  gradle/scripts/log4j-test.properties
Labels: testing improvement

#3195 Run the PR label check whenever the HEAD commit changes to ensure it is applied to the final commit of each PR
  .github/workflows/pr_labels.yml
Labels: build improvement

#3211 Serialize missing field `createDefaultIfEmpty` into streaming aggregate plan continuations
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryStreamingAggregationPlan.java
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/aggregate-index-tests.yamsql
Labels: bug fix

#3215 Fix continuation deserialization errors by deserializing streaming aggregate plans in the correct order
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryStreamingAggregationPlan.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBStreamAggregationTest.java
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/aggregate-index-tests-count.yamsql
Labels: bug fix
