Repository FoundationDB/fdb-record-layer, pull requests merged in 2025-04, with the labels that each got.

#3267 Remove a bunch of blank lines in unsupported methods
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalPreparedStatement.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalResultSet.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalStatement.java
Labels: cleanup

#3277 Remove get_old_version step from release build
  .github/workflows/release.yml
Labels: build improvement

#3283 Fix warning from sphinxDocs about missing _static directory.
  gradle/sphinx.gradle
Labels: build improvement

#3276 Fix wasNull state across toString() calls in RowStruct
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalStruct.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/RowStruct.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/RowStructTest.java
Labels: bug fix

#3273 Rework SqlLineTest so that it actually interacts with the database
  fdb-relational-cli/src/test/java/com/apple/foundationdb/relational/cli/SQLLineTest.java
Labels: testing improvement

#3287 Downgrade protobuf version back to 3.25.5 and grpc common proto to 2.37.0
  gradle/libs.versions.toml
Labels: dependencies

#3192 Added workflow for creating branches for patch releases
  .github/workflows/create_branch.yml
Labels: build improvement

#3289 Decrease the number of builds compared during mixed mode to the most recent 10
  yaml-tests/yaml-tests.gradle
Labels: build improvement

#3290 Decrease the number of builds compared during mixed mode to the most recent 10
  yaml-tests/yaml-tests.gradle
Labels: build improvement

#3280 Support SQL Table Valued Functions
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/BuiltInTableFunction.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/PlannerRuleSet.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/TableFunctionExpression.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/matching/structure/RelationalExpressionMatchers.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/CompatibleTypeEvolutionPredicate.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/CardinalitiesProperty.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/DerivationsProperty.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/DistinctRecordsProperty.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/OrderingProperty.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/PrimaryKeyProperty.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/StoredRecordProperty.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/ImplementTableFunctionRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/Type.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/FirstOrDefaultStreamingValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/RangeValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/StreamingValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/explain/ExplainPlanVisitor.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryTableFunctionPlan.java
  fdb-record-layer-core/src/main/proto/record_cursor.proto
  fdb-record-layer-core/src/main/proto/record_query_plan.proto
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/exceptions/ErrorCode.java
  fdb-relational-core/src/main/antlr/RelationalLexer.g4
  fdb-relational-core/src/main/antlr/RelationalParser.g4
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/LogicalOperator.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/SemanticAnalyzer.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/functions/SqlFunctionCatalogImpl.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/BaseVisitor.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/DelegatingVisitor.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/ExpressionVisitor.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/IdentifierVisitor.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/QueryVisitor.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/TypedVisitor.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/util/TypeUtils.java
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/table-functions.metrics.binpb
  yaml-tests/src/test/resources/table-functions.metrics.yaml
  yaml-tests/src/test/resources/table-functions.yamsql
Labels: enhancement

#3294 Updating release notes for 4.2.2.1
  docs/sphinx/source/ReleaseNotes.md
Labels: documentation

#3271 Synthetic record orphan policy
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/JoinedRecordType.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/SyntheticRecordType.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/UnnestedRecordType.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBTypedRecordStore.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/ValueIndexScrubbingToolsDangling.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/ValueIndexScrubbingToolsMissing.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/JoinedRecordTypeTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubberTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/UnnestedRecordTypeTest.java
Labels: enhancement, breaking change

#3284 When downloading old servers, only cache latest version for 10 minutes
  yaml-tests/yaml-tests.gradle
Labels: build improvement

#3293 Rollback UUID support in SQL Layer
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/Type.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/TypeTest.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/metadata/DataType.java
  fdb-relational-core/src/main/antlr/RelationalParser.g4
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/RowStruct.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/MessageTuple.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/metadata/DataTypeUtils.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/metadata/RecordLayerSchemaTemplate.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/metadata/serde/FileDescriptorSerializer.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/SemanticAnalyzer.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/compare/JDBCDatabaseMetaData.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/compare/JDBCRelationalResultSet.java
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/TypeConversion.java
  fdb-relational-grpc/src/test/java/com/apple/foundationdb/relational/jdbc/AbstractMockResultSet.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/QueryInterpreter.java
  yaml-tests/src/main/proto/uuid_proto_test.proto
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/uuid-proto.yamsql
  yaml-tests/src/test/resources/uuid.metrics.binpb
  yaml-tests/src/test/resources/uuid.metrics.yaml
  yaml-tests/src/test/resources/uuid.yamsql
  yaml-tests/yaml-tests.gradle
Labels: bug fix, breaking change

#3298 Index scrubbing should support range id & range reset
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexBuildState.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexScrubbing.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubDangling.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubMissing.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingSubspaces.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexOperationBaseBuilder.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubber.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexing/IndexingRangeSet.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreOpeningTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubberTest.java
Labels: enhancement

#3301 Fix connection name in Multiserver configs in YAML-tests
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/SimpleYamlConnection.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/JDBCMultiServerConfig.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/connectionfactory/EmbeddedYamlConnectionFactory.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/connectionfactory/JDBCInProcessYamlConnectionFactory.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/connectionfactory/MultiServerConnectionFactory.java
Labels: testing improvement

#3306 Make INDEX_SCRUBBED_INDEX_RANGES unique + more
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexScrubbing.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubDangling.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingScrubMissing.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingSubspaces.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubber.java
Labels: bug fix, breaking change

#3310 Fix getMixedModeVersion() to match display name
  gradle/testing.gradle
Labels: build improvement

#3316 Upgrade to gradle 8
  fdb-record-layer-core-shaded/fdb-record-layer-core-shaded.gradle
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: build improvement

#3317 Extra cleanup for the index scrubbing code
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingSubspaces.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexing/IndexingRangeSet.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubberTest.java
Labels: enhancement, testing improvement, cleanup

#3309 Prevent setting the format version to an unsupported version
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreFormatVersionTest.java
Labels: bug fix

#3302 Fix potential NPE due to exception not having an underlying message
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/CascadesPlanner.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/UnableToPlanException.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBNestedRepeatedQueryTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/GroupByTest.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/util/ExceptionUtil.java
Labels: bug fix

#3304 Transition FormatVersion from constants to an enum
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBMetaDataStore.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoredSizes.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBTypedRecordStore.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FormatVersion.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingByIndex.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexOperationBaseBuilder.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java
  fdb-record-layer-core/src/main/proto/record_metadata.proto
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreConcurrentTestBase.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreCountRecordsTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreFormatVersionTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreSplitRecordsTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreTestBase.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FormatVersionTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FormatVersionTestUtils.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerIndexFromIndexTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/RemoteFetchOldVersionTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexes/VersionIndexTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/storestate/FDBRecordStoreStateCacheTest.java
  fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestUtils.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/RecordLayerConfig.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/storage/StoreConfig.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/TransactionBoundDatabaseWithEnumTest.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/Command.java
Labels: enhancement, documentation

#3312 Remove deprecated IndexingByRecords module
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingByRecords.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMultiTargetByRecords.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexOperationBaseBuilder.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreIndexTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMultiTargetTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerSimpleTest.java
Labels: breaking change

#3323 fix for pull up of null-on-empty bug
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Reference.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/rules/PullUpNullOnEmptyRule.java
  yaml-tests/src/test/resources/aggregate-empty-table.metrics.binpb
  yaml-tests/src/test/resources/aggregate-empty-table.metrics.yaml
  yaml-tests/src/test/resources/aggregate-index-tests-count-empty.metrics.binpb
  yaml-tests/src/test/resources/aggregate-index-tests-count-empty.metrics.yaml
  yaml-tests/src/test/resources/aggregate-index-tests-count.metrics.binpb
  yaml-tests/src/test/resources/aggregate-index-tests-count.metrics.yaml
  yaml-tests/src/test/resources/aggregate-index-tests.metrics.binpb
  yaml-tests/src/test/resources/aggregate-index-tests.metrics.yaml
  yaml-tests/src/test/resources/catalog.metrics.binpb
  yaml-tests/src/test/resources/catalog.metrics.yaml
  yaml-tests/src/test/resources/create-drop.metrics.binpb
  yaml-tests/src/test/resources/create-drop.metrics.yaml
  yaml-tests/src/test/resources/field-index-tests-proto.metrics.binpb
  yaml-tests/src/test/resources/field-index-tests-proto.metrics.yaml
  yaml-tests/src/test/resources/groupby-tests.metrics.binpb
  yaml-tests/src/test/resources/groupby-tests.metrics.yaml
  yaml-tests/src/test/resources/null-operator-tests.metrics.binpb
  yaml-tests/src/test/resources/null-operator-tests.metrics.yaml
  yaml-tests/src/test/resources/primary-key-tests.metrics.binpb
  yaml-tests/src/test/resources/primary-key-tests.metrics.yaml
  yaml-tests/src/test/resources/standard-tests-metadata.metrics.binpb
  yaml-tests/src/test/resources/standard-tests-metadata.metrics.yaml
  yaml-tests/src/test/resources/standard-tests-proto.metrics.binpb
  yaml-tests/src/test/resources/standard-tests-proto.metrics.yaml
  yaml-tests/src/test/resources/standard-tests.metrics.binpb
  yaml-tests/src/test/resources/standard-tests.metrics.yaml
  yaml-tests/src/test/resources/union-empty-tables.metrics.binpb
  yaml-tests/src/test/resources/union-empty-tables.metrics.yaml
  yaml-tests/src/test/resources/union.metrics.binpb
  yaml-tests/src/test/resources/union.metrics.yaml
Labels: bug fix

#3327 query uses grouping index with Is_Null predicate
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/GroupByExpression.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/GroupByQueryTests.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/QueryTestUtils.java
Labels: bug fix
