Repository FoundationDB/fdb-record-layer, pull requests merged in 2025-08, with the labels that each got.

#3515 Interpret full-supported UUID type correctly in JDBC server
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/metadata/DataType.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/metadata/DataTypeUtils.java
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/TypeConversion.java
Labels: enhancement

#3534 Fully qualify teamscale action
  .github/workflows/teamscale_upload.yml
Labels: build improvement

#3510 Bring back full support for UUID
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/Type.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/TypeTest.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalArrayBuilder.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalStructBuilder.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/metadata/DataType.java
  fdb-relational-core/src/main/antlr/RelationalParser.g4
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/EmbeddedRelationalArray.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/EmbeddedRelationalStruct.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/metadata/RecordLayerSchemaTemplate.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/metadata/serde/FileDescriptorSerializer.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/Literals.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/SemanticAnalyzer.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/RelationalArrayTest.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/StandardQueryTests.java
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/RelationalArrayFacade.java
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/RelationalStructFacade.java
  fdb-relational-grpc/src/test/java/com/apple/foundationdb/relational/jdbc/RelationalStructFacadeTest.java
  fdb-relational-jdbc/src/main/java/com/apple/foundationdb/relational/jdbc/ParameterHelper.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlTestExtension.java
  yaml-tests/src/test/java/YamlIntegrationDisabledPlannerRewritesTests.java
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/disabled-planner-rewrites/uuid-proto.yamsql
  yaml-tests/src/test/resources/disabled-planner-rewrites/uuid.metrics.binpb
  yaml-tests/src/test/resources/disabled-planner-rewrites/uuid.metrics.yaml
  yaml-tests/src/test/resources/disabled-planner-rewrites/uuid.yamsql
  yaml-tests/src/test/resources/uuid-proto.yamsql
  yaml-tests/src/test/resources/uuid.metrics.binpb
  yaml-tests/src/test/resources/uuid.metrics.yaml
  yaml-tests/src/test/resources/uuid.yamsql
Labels: enhancement, relational

#3531 Handle metrics for the same query but with different setups
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlExecutionContext.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/QueryConfig.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/QueryExecutor.java
  yaml-tests/src/main/proto/planner_metrics.proto
  yaml-tests/src/test/java/TransactionSetupTest.java
  yaml-tests/src/test/resources/transaction-setup/shouldPass/double-query-metrics.metrics.binpb
  yaml-tests/src/test/resources/transaction-setup/shouldPass/double-query-metrics.metrics.yaml
  yaml-tests/src/test/resources/transaction-setup/shouldPass/double-query-metrics.yamsql
Labels: testing improvement

#3357 Support isDistinctFrom and isNotDistinctFrom operators
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/Comparisons.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/RangeConstraints.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/RelOpValue.java
  fdb-record-layer-core/src/main/proto/record_query_plan.proto
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/expressions/QueryExpressionTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/BooleanValueTest.java
  fdb-relational-core/src/main/antlr/RelationalParser.g4
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/functions/SqlFunctionCatalogImpl.java
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/distinct-from.metrics.binpb
  yaml-tests/src/test/resources/distinct-from.metrics.yaml
  yaml-tests/src/test/resources/distinct-from.yamsql
Labels: enhancement

#3542 Fix insertion of Struct with Enum
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/MessageHelpers.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/PromoteValue.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/TableWithEnumTest.java
  fdb-relational-core/src/testFixtures/java/com/apple/foundationdb/relational/utils/ArrayAssert.java
  fdb-relational-core/src/testFixtures/java/com/apple/foundationdb/relational/utils/ResultSetAssert.java
  fdb-relational-core/src/testFixtures/java/com/apple/foundationdb/relational/utils/TestSchemas.java
Labels: bug fix

#3553 Add a metric to measure generate continued plan
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/metrics/RelationalMetric.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/PlanGenerator.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/metric/RecordLayerMetricCollectorTest.java
Labels: enhancement

#3551 Fix for Lucene block leaks on file deletion
  fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java
  fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestValidator.java
  fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java
  fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/MockedFDBDirectory.java
Labels: bug fix

#3552 Deprecate synchronized indexing controls
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexOperationBaseBuilder.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildIndexTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildJoinedIndexTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildRankIndexTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildSumIndexTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildUnnestedIndexTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildValueIndexTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildVersionIndexTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerIndexFromIndexTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMultiTargetTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerSimpleTest.java
Labels: breaking change

#3535 Use thenAccept instead of thenApply
  fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexScrubbingToolsMissing.java
Labels: cleanup

#3541 Add serialized plan complexity and hash to the continuation info in EXPLAIN
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/QueryPlan.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/ExplainTests.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/storage/BackingLocatableResolverStoreTest.java
  fdb-relational-core/src/testFixtures/java/com/apple/foundationdb/relational/utils/ResultSetAssert.java
Labels: enhancement
