Repository FoundationDB/fdb-record-layer, pull requests merged in 2025-03, with the labels that each got.

#3222 Fix unstable hash for NULL literal
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/Type.java
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/boolean.yamsql
  yaml-tests/src/test/resources/functions.yamsql
Labels: bug fix

#3205 Introduce a new `Option` to set `asyncToSync` timeout.
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/Options.java
  fdb-relational-server/src/main/java/com/apple/foundationdb/relational/server/FRL.java
Labels: enhancement, bug fix

#3212 Prevent caching `INSERT` statements
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/AstNormalizer.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/PlanGenerator.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/AstNormalizerTests.java
Labels: performance, bug fix

#3200 Test concurrent indexing sessions without sync lock
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerIndexFromIndexTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMultiTargetTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTest.java
Labels: testing improvement

#3230 `RecordQueryExplodePlan` plan adheres to `skip` and `limit` requirements
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryExplodePlan.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/plans/ExplodePlanTest.java
Labels: bug fix

#3221 `EXISTS` queries now honor continuation from previous runs to avoid infinite loops
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/RecordCursor.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/FutureCursor.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryFirstOrDefaultPlan.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/RecordCursorTest.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/storage/BackingLocatableResolverStore.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/storage/BackingLocatableResolverStoreTest.java
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/join-tests.yamsql
  yaml-tests/src/test/resources/select-a-star.metrics.binpb
  yaml-tests/src/test/resources/select-a-star.metrics.yaml
  yaml-tests/src/test/resources/select-a-star.yamsql
Labels: bug fix

#3217 Create a yaml test config that runs two servers with the same version
  gradle/testing.gradle
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlTestExtension.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/EmbeddedConfig.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/ExternalMultiServerConfig.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/JDBCInProcessConfig.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/configs/JDBCMultiServerConfig.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/connectionfactory/EmbeddedYamlConnectionFactory.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/connectionfactory/ExternalServerYamlConnectionFactory.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/connectionfactory/JDBCInProcessYamlConnectionFactory.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/connectionfactory/MultiServerConnectionFactory.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/connectionfactory/package-info.java
  yaml-tests/src/test/java/MultiServerConnectionFactoryTest.java
  yaml-tests/yaml-tests.gradle
Labels: testing improvement

#3223 Write PMD output to consoleOutput during build
  gradle/check.gradle
Labels: build improvement

#3207 Fix deserialization of continuations for queries that contain LIKE
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/PatternForLikeValue.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/LikeOperatorValueTest.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/CustomYamlConstructor.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/Block.java
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/like.yamsql
Labels: bug fix

#3228 Enable force continuations mode on all `YamlIntegrationTest`s
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/QueryExecutor.java
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/aggregate-empty-table.metrics.binpb
  yaml-tests/src/test/resources/aggregate-empty-table.metrics.yaml
  yaml-tests/src/test/resources/aggregate-empty-table.yamsql
  yaml-tests/src/test/resources/bitmap-aggregate-index.yamsql
  yaml-tests/src/test/resources/boolean.yamsql
  yaml-tests/src/test/resources/catalog.metrics.binpb
  yaml-tests/src/test/resources/catalog.metrics.yaml
  yaml-tests/src/test/resources/catalog.yamsql
  yaml-tests/src/test/resources/create-drop.metrics.binpb
  yaml-tests/src/test/resources/create-drop.metrics.yaml
  yaml-tests/src/test/resources/create-drop.yamsql
  yaml-tests/src/test/resources/enum.yamsql
  yaml-tests/src/test/resources/field-index-tests-proto.metrics.binpb
  yaml-tests/src/test/resources/field-index-tests-proto.metrics.yaml
  yaml-tests/src/test/resources/field-index-tests-proto.yamsql
  yaml-tests/src/test/resources/functions.yamsql
  yaml-tests/src/test/resources/groupby-tests.metrics.binpb
  yaml-tests/src/test/resources/groupby-tests.metrics.yaml
  yaml-tests/src/test/resources/groupby-tests.yamsql
  yaml-tests/src/test/resources/insert-enum.yamsql
  yaml-tests/src/test/resources/inserts-updates-deletes.yamsql
  yaml-tests/src/test/resources/null-operator-tests.metrics.binpb
  yaml-tests/src/test/resources/null-operator-tests.metrics.yaml
  yaml-tests/src/test/resources/null-operator-tests.yamsql
  yaml-tests/src/test/resources/primary-key-tests.metrics.binpb
  yaml-tests/src/test/resources/primary-key-tests.metrics.yaml
  yaml-tests/src/test/resources/primary-key-tests.yamsql
  yaml-tests/src/test/resources/recursive-cte.yamsql
  yaml-tests/src/test/resources/standard-tests-metadata.metrics.binpb
  yaml-tests/src/test/resources/standard-tests-metadata.metrics.yaml
  yaml-tests/src/test/resources/standard-tests-metadata.yamsql
  yaml-tests/src/test/resources/standard-tests-proto.metrics.binpb
  yaml-tests/src/test/resources/standard-tests-proto.metrics.yaml
  yaml-tests/src/test/resources/standard-tests-proto.yamsql
  yaml-tests/src/test/resources/standard-tests.metrics.binpb
  yaml-tests/src/test/resources/standard-tests.metrics.yaml
  yaml-tests/src/test/resources/standard-tests.yamsql
  yaml-tests/src/test/resources/subquery-tests.metrics.binpb
  yaml-tests/src/test/resources/subquery-tests.metrics.yaml
  yaml-tests/src/test/resources/subquery-tests.yamsql
  yaml-tests/src/test/resources/union-empty-tables.metrics.binpb
  yaml-tests/src/test/resources/union-empty-tables.metrics.yaml
  yaml-tests/src/test/resources/union-empty-tables.yamsql
  yaml-tests/src/test/resources/union.metrics.binpb
  yaml-tests/src/test/resources/union.metrics.yaml
  yaml-tests/src/test/resources/union.yamsql
Labels: testing improvement

#3235 Fix path to FDB logo in README.md
  README.md
Labels: documentation

#3225 Fix gradle warnings in prb
  actions/run-gradle/action.yml
  gradle/publishing.gradle
Labels: build improvement

#3236 Change documentation link in readme to point to github pages
  README.md
Labels: documentation

#3233 Run Mixed Mode Tests during the release parallel to the other tests
  .github/workflows/mixed_mode_test.yml
  .github/workflows/patch_release.yml
  .github/workflows/release.yml
  .gitignore
  actions/release-build-publish/action.yml
  build/create_release_notes.py
  build/publish-mixed-mode-results.py
Labels: build improvement

#3243 Add --warning-mode all to all our builds
  actions/run-gradle/action.yml
Labels: build improvement

#3241 Do not drop AllTime leaderboard if deleteBefore is Long.Max_VALUE
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboard.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardIndexMaintainer.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/TimeWindowLeaderboardWindowUpdate.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/leaderboard/LeaderboardIndexTest.java
Labels: bug fix

#3239 Add illegal version tests to SupportedVersionTest
  yaml-tests/src/test/java/SupportedVersionTest.java
  yaml-tests/src/test/resources/supported-version/illegal-version-at-block.yamsql
  yaml-tests/src/test/resources/supported-version/illegal-version-at-file.yamsql
  yaml-tests/src/test/resources/supported-version/illegal-version-at-query.yamsql
Labels: testing improvement

#3248 SchemaTemplateSerDeTests: Replace ibm's Pair with our NonnullPair
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/metadata/SchemaTemplateSerDeTests.java
Labels: testing improvement

#3250 Add missing explicit dependencies for gradle tasks
  fdb-record-layer-jmh/fdb-record-layer-jmh.gradle
  fdb-relational-cli/fdb-relational-cli.gradle
Labels: build improvement

#3244 Remove -Xverify:none from build
  actions/run-gradle/action.yml
Labels: build improvement

#3257 Remove unused build files
  build.py
  build/Dockerfile.build
  build/Dockerfile.fdbserver
  build/Dockerfile.standalone-tests
  build/docker-compose.yaml
  build/fdb_create_cluster_file.bash
  build/fdb_docker_start.bash
  build/update_release_notes.bash
  build/update_release_notes.py
Labels: build improvement, cleanup

#3256 Remove Artifactory publishing logic from gradle build
  build.gradle
  fdb-record-layer-core-shaded/fdb-record-layer-core-shaded.gradle
  gradle/libs.versions.toml
  gradle/publishing.gradle
Labels: build improvement, cleanup

#3245 Queries using versions now use a serialization that requires 4.1
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/VersionValue.java
Labels: breaking change

#3260 Prepare for upgrade to Protobuf 4 by removing deprecated or removed calls
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidator.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/metadata/MetaDataEvolutionValidatorTestV3.java
  fdb-relational-server/src/test/java/com/apple/foundationdb/relational/server/RelationalServerTest.java
  yaml-tests/yaml-tests.gradle
Labels: build improvement

#3255 Change some error messages to format with Locale.ROOT
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/util/Assert.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/metadata/SchemaTemplateSerDeTests.java
Labels: bug fix

#3258 Update protobuf dependency to 4.30.1 and grpc-commonProtos dependency to 2.54.1
  gradle/libs.versions.toml
Labels: dependencies

#3270 Remove deprecated DatabaseTemplate
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/catalog/DatabaseTemplate.java
Labels: breaking change

#3269 Remove a bunch of references to @ExcludeFromJacocoGeneratedReport
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalDatabaseMetaData.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalDriver.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalPreparedStatement.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalResultSet.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalResultSetMetaData.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalStatement.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/SqlTypeNamesSupport.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/util/Assert.java
  fdb-relational-cli/src/main/java/com/apple/foundationdb/relational/cli/sqlline/Customize.java
  fdb-relational-cli/src/main/java/sqlline/SetSchema.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/ProtobufDataBuilder.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/metrics/NoOpMetricRegistry.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/EmbeddedRelationalConnection.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/ErrorCapturingResultSet.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/catalog/systables/SystemTableRegistry.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/ddl/RecordLayerMetadataOperationsFactory.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/ddl/RecordLayerSetStoreStateConstantAction.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/cache/MultiStageCache.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/cache/RelationalPlanCache.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/memory/InMemorySchemaTemplateCatalog.java
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/RelationalResultSetFacade.java
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/RelationalResultSetMetaDataFacade.java
  fdb-relational-jdbc/src/main/java/com/apple/foundationdb/relational/jdbc/JDBCRelationalConnection.java
  fdb-relational-jdbc/src/main/java/com/apple/foundationdb/relational/jdbc/JDBCRelationalStatement.java
  fdb-relational-server/src/main/java/com/apple/foundationdb/relational/server/RelationalServer.java
Labels: testing improvement

#3268 Add cleanup to list of potential labels for PRs
  build/release-notes-config.json
Labels: documentation, build improvement

#3278 Remove more @ExcludeFromJacocoGeneratedReport
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/ddl/NoOpQueryFactory.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/HollowTransactionManager.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/ddl/NoOpMetadataOperationsFactory.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/transactionbound/catalog/HollowSchemaTemplateCatalog.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/transactionbound/catalog/HollowStoreCatalog.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/api/ddl/AbstractMetadataOperationsFactory.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/api/ddl/AbstractQueryFactory.java
Labels: testing improvement

#3279 Fix release note since 4.2.1.0 release did not get published to maven central
  docs/sphinx/source/ReleaseNotes.md
Labels: documentation

#3198 Add support for UUID as primitive type in SQL
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/SemanticException.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/Type.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/typing/TypeRepository.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/FieldValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/IndexEntryObjectValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/MessageHelpers.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/PromoteValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/RecordConstructorValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/RelOpValue.java
  fdb-record-layer-core/src/main/proto/record_query_plan.proto
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreCrudTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreUniqueIndexTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreIndexTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/query/FDBRecordStoreQueryTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/BooleanValueTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/TypeRepositoryTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/TypeTest.java
  fdb-record-layer-core/src/test/proto/test_records_uuid.proto
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalPreparedStatement.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalStruct.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/SqlTypeNamesSupport.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/metadata/DataType.java
  fdb-relational-core/src/main/antlr/RelationalParser.g4
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/RowStruct.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/SqlTypeSupport.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/AbstractRecordLayerResultSet.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/EmbeddedRelationalPreparedStatement.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/ErrorCapturingResultSet.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/MessageTuple.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/metadata/DataTypeUtils.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/metadata/RecordLayerSchemaTemplate.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/metadata/serde/FileDescriptorSerializer.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/SemanticAnalyzer.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/compare/JDBCDatabaseMetaData.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/compare/JDBCRelationalResultSet.java
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/RelationalResultSetFacade.java
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/RelationalStructFacade.java
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/TypeConversion.java
  fdb-relational-grpc/src/main/proto/grpc/relational/jdbc/v1/column.proto
  fdb-relational-grpc/src/test/java/com/apple/foundationdb/relational/jdbc/AbstractMockResultSet.java
  fdb-relational-grpc/src/test/java/com/apple/foundationdb/relational/jdbc/MockResultSetRow.java
  fdb-relational-jdbc/src/main/java/com/apple/foundationdb/relational/jdbc/JDBCRelationalPreparedStatement.java
  fdb-relational-jdbc/src/main/java/com/apple/foundationdb/relational/jdbc/ParameterHelper.java
  fdb-relational-server/src/main/java/com/apple/foundationdb/relational/server/FRL.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/AbstractAggregateResultSet.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/CustomTag.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/CustomYamlConstructor.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/Matchers.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/QueryInterpreter.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/parameterinjection/PrimitiveParameter.java
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/uuid.metrics.binpb
  yaml-tests/src/test/resources/uuid.metrics.yaml
  yaml-tests/src/test/resources/uuid.yamsql
Labels: enhancement
