Repository FoundationDB/fdb-record-layer, pull requests merged in 2025-10, with the labels that each got.

#3650 remove CONTINUATION_CONTAINS_COMPILED_STATEMENT usage
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/Options.java
  fdb-relational-api/src/testFixtures/java/com/apple/foundationdb/relational/utils/OptionsTestHelper.java
  fdb-relational-core/src/main/antlr/RelationalParser.g4
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/AstNormalizer.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/OptionsUtils.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/QueryPlan.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/JoinWithLimitTest.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/ExplainTests.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/ForceContinuationQueryTests.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/GroupByQueryTests.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/QueryWithContinuationTest.java
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/TypeConversion.java
Labels: cleanup

#3577 Implementation of grouping size aggregator
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/SizeStatisticsCollectorCursor.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/SizeStatisticsGroupedResults.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/SizeStatisticsGroupingContinuation.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/SizeStatisticsGroupingCursor.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/cursors/SizeStatisticsResults.java
  fdb-record-layer-core/src/main/proto/record_cursor.proto
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/cursors/SizeStatisticsGroupingCursorTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/cursors/SizeStatisticsResultsTest.java
Labels: enhancement

#3638 Make YAML tests pass connection options to servers for transaction setups
  fdb-relational-server/src/main/java/com/apple/foundationdb/relational/server/jdbc/v1/TransactionRequestHandler.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/SetupBlock.java
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/setup-with-connection-options.yamsql
Labels: testing improvement

#3637 Improved documentation of CTEs and documentation validation
  docs/sphinx/source/reference/sql_commands/DQL/WITH.diagram
  docs/sphinx/source/reference/sql_commands/DQL/WITH.rst
  fdb-relational-core/src/main/antlr/RelationalLexer.g4
  fdb-relational-core/src/main/antlr/RelationalParser.g4
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/DelegatingVisitor.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/QueryVisitor.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/DelegatingVisitorTest.java
  yaml-tests/src/test/java/DocumentationQueriesTests.java
  yaml-tests/src/test/resources/documentation-queries/with-documentation-queries.yamsql
  yaml-tests/src/test/resources/recursive-cte.metrics.binpb
  yaml-tests/src/test/resources/recursive-cte.metrics.yaml
  yaml-tests/src/test/resources/recursive-cte.yamsql
Labels: documentation

#3607 Make Lucene serialization able to encrypt, …
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/CompressedAndEncryptedSerializerState.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/TransformedRecordSerializerState.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/properties/RecordLayerPropertyStorage.java
  fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneEvents.java
  fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordContextProperties.java
  fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java
  fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/LuceneSerializer.java
  fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneQueryTest.java
  fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java
  fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneSerializerTest.java
  fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryFailuresTest.java
  fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java
Labels: enhancement

#3647 Support SQL `CAST` operator
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/SemanticException.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/AbstractArrayConstructorValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/CastValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/PromoteValue.java
  fdb-record-layer-core/src/main/proto/record_query_plan.proto
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/values/CastValueTest.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/exceptions/ErrorCode.java
  fdb-relational-core/src/main/antlr/RelationalParser.g4
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/BaseVisitor.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/ExpressionVisitor.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/util/ExceptionUtil.java
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/RelationalArrayFacade.java
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/arrays.yamsql
  yaml-tests/src/test/resources/cast-tests.metrics.binpb
  yaml-tests/src/test/resources/cast-tests.metrics.yaml
  yaml-tests/src/test/resources/cast-tests.yamsql
  yaml-tests/src/test/resources/enum.yamsql
Labels: enhancement, relational
