Repository FoundationDB/fdb-record-layer, pull requests merged in 2025-07, with the labels that each got.

#3457 Update the Maven Central publishing URL to avoid sunset service
  .github/workflows/release.yml
  build.gradle
  docs/sphinx/source/ReleaseNotes.md
Labels: build improvement

#3443 Fix eager constant folding in `RelOpValue` and other fixes
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/TreeLike.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/QueryPredicate.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/PredicateComplexityProperty.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/AbstractArrayConstructorValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/AndOrValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/BooleanValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/ExistsValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/InOpValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/LikeOperatorValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/NotValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/PromoteValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/RelOpValue.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/simplification/EvaluateConstantPromotionRule.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/translation/MaxMatchMap.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/BooleanValueTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/debug/DebuggerWithSymbolTables.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/Expression.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/LogicalOperator.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/TautologicalValue.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/functions/SqlFunctionCatalog.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/functions/SqlFunctionCatalogImpl.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/BaseVisitor.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/DdlVisitor.java
  yaml-tests/src/test/resources/between.metrics.binpb
  yaml-tests/src/test/resources/between.metrics.yaml
  yaml-tests/src/test/resources/catalog.metrics.binpb
  yaml-tests/src/test/resources/catalog.metrics.yaml
  yaml-tests/src/test/resources/create-drop.metrics.binpb
  yaml-tests/src/test/resources/create-drop.metrics.yaml
  yaml-tests/src/test/resources/disabled-planner-rewrites/sql-functions.yamsql
  yaml-tests/src/test/resources/indexed-functions.metrics.binpb
  yaml-tests/src/test/resources/indexed-functions.metrics.yaml
  yaml-tests/src/test/resources/literal-tests.yamsql
  yaml-tests/src/test/resources/nested-with-nulls-proto.metrics.binpb
  yaml-tests/src/test/resources/nested-with-nulls-proto.metrics.yaml
  yaml-tests/src/test/resources/nested-with-nulls.metrics.binpb
  yaml-tests/src/test/resources/nested-with-nulls.metrics.yaml
  yaml-tests/src/test/resources/sql-functions.metrics.binpb
  yaml-tests/src/test/resources/sql-functions.metrics.yaml
  yaml-tests/src/test/resources/sql-functions.yamsql
  yaml-tests/src/test/resources/subquery-tests.metrics.binpb
  yaml-tests/src/test/resources/subquery-tests.metrics.yaml
Labels: bug fix

#3429 Add support for AutoCommit(false)
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/AbstractEmbeddedStatement.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/EmbeddedRelationalConnection.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/EmbeddedRelationalStatement.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/RecordLayerResultSet.java
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/grpc/GrpcSQLExceptionUtil.java
  fdb-relational-grpc/src/main/proto/grpc/relational/jdbc/v1/jdbc.proto
  fdb-relational-jdbc/src/main/java/com/apple/foundationdb/relational/jdbc/JDBCRelationalConnection.java
  fdb-relational-jdbc/src/main/java/com/apple/foundationdb/relational/jdbc/JDBCRelationalStatement.java
  fdb-relational-jdbc/src/main/java/com/apple/foundationdb/relational/jdbc/JdbcConnectionException.java
  fdb-relational-jdbc/src/main/java/com/apple/foundationdb/relational/jdbc/StatefulServerConnection.java
  fdb-relational-jdbc/src/test/java/com/apple/foundationdb/relational/jdbc/JDBCAutoCommitTest.java
  fdb-relational-jdbc/src/test/java/com/apple/foundationdb/relational/jdbc/JDBCAutoCommitTestRealNetwork.java
  fdb-relational-server/src/main/java/com/apple/foundationdb/relational/server/FRL.java
  fdb-relational-server/src/main/java/com/apple/foundationdb/relational/server/TransactionalToken.java
  fdb-relational-server/src/main/java/com/apple/foundationdb/relational/server/jdbc/v1/JDBCService.java
  fdb-relational-server/src/main/java/com/apple/foundationdb/relational/server/jdbc/v1/TransactionRequestHandler.java
  gradle/testing.gradle
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlTestExtension.java
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/transactions-tests.yamsql
Labels: enhancement

#3464 Rename shouldCommit back to canCommit
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/AbstractEmbeddedStatement.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/EmbeddedRelationalConnection.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/EmbeddedRelationalStatement.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/RecordLayerResultSet.java
Labels: cleanup

#3460 Escape the ' character in the loggable method to help with log parser frameworks.
  fdb-extensions/src/main/java/com/apple/foundationdb/tuple/ByteArrayUtil2.java
  fdb-extensions/src/test/java/com/apple/foundationdb/tuple/ByteArrayUtil2Test.java
  fdb-extensions/src/test/java/com/apple/foundationdb/tuple/TupleTest.java
Labels: bug fix

#3393 Re-enable force continuation tests in Yaml
  yaml-tests/src/test/resources/aggregate-index-tests-count.yamsql
  yaml-tests/src/test/resources/aggregate-index-tests.yamsql
  yaml-tests/src/test/resources/bitmap-aggregate-index.yamsql
  yaml-tests/src/test/resources/boolean.yamsql
  yaml-tests/src/test/resources/catalog.yamsql
  yaml-tests/src/test/resources/create-drop.metrics.binpb
  yaml-tests/src/test/resources/create-drop.metrics.yaml
  yaml-tests/src/test/resources/field-index-tests-proto.yamsql
  yaml-tests/src/test/resources/functions.yamsql
  yaml-tests/src/test/resources/groupby-tests.yamsql
  yaml-tests/src/test/resources/join-tests.yamsql
  yaml-tests/src/test/resources/like.yamsql
  yaml-tests/src/test/resources/null-operator-tests.yamsql
  yaml-tests/src/test/resources/primary-key-tests.yamsql
  yaml-tests/src/test/resources/select-a-star.yamsql
  yaml-tests/src/test/resources/standard-tests-metadata.yamsql
  yaml-tests/src/test/resources/standard-tests-proto.yamsql
  yaml-tests/src/test/resources/standard-tests.yamsql
  yaml-tests/src/test/resources/subquery-tests.yamsql
  yaml-tests/src/test/resources/union-empty-tables.yamsql
  yaml-tests/src/test/resources/union.yamsql
Labels: testing improvement

#3476 Fix transactional insert throwing No Value Present in server
  fdb-relational-jdbc/src/test/java/com/apple/foundationdb/relational/jdbc/JDBCAutoCommitTest.java
  fdb-relational-server/src/main/java/com/apple/foundationdb/relational/server/jdbc/v1/TransactionRequestHandler.java
Labels: bug fix

#3466 revive and move `PlannerRepl` into its own component
  .idea/gradle.xml
  fdb-record-layer-core/fdb-record-layer-core.gradle
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/CascadesPlanner.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/debug/Debugger.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/debug/DebuggerWithSymbolTables.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/debug/State.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/explain/PlannerGraphVisitor.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryRecursiveUnionPlan.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreConcurrentTestBase.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/rules/DecorrelateValuesRuleTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/rules/PredicatePushDownRuleTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/cascades/rules/SelectMergeRuleTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/query/plan/debug/ReplRunner.java
  fdb-record-layer-debugger/fdb-record-layer-debugger.gradle
  fdb-record-layer-debugger/src/main/java/com/apple/foundationdb/record/query/plan/cascades/debug/Commands.java
  fdb-record-layer-debugger/src/main/java/com/apple/foundationdb/record/query/plan/cascades/debug/PlannerRepl.java
  fdb-record-layer-debugger/src/main/java/com/apple/foundationdb/record/query/plan/cascades/debug/Processors.java
  fdb-record-layer-debugger/src/main/java/com/apple/foundationdb/record/query/plan/cascades/debug/package-info.java
  fdb-record-layer-debugger/src/main/javadoc/overview.html
  fdb-record-layer-debugger/src/test/java/com/apple/foundationdb/record/query/plan/cascades/debug/ReplRunner.java
  fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTestUtils.java
  fdb-relational-cli/fdb-relational-cli.gradle
  fdb-relational-cli/src/main/java/sqlline/PlannerDebuggerCommandHandler.java
  fdb-relational-core/fdb-relational-core.gradle
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/Utils.java
  scripts/plannerRepl.sh
  settings.gradle
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/CustomYamlConstructor.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/DebugPlanner.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/block/TestBlock.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/DebuggerImplementation.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/QueryCommand.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/QueryConfig.java
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/java/com/apple/foundationdb/relational/yamltests/server/SemanticVersionTest.java
  yaml-tests/src/test/resources/cte.metrics.binpb
  yaml-tests/src/test/resources/cte.metrics.yaml
  yaml-tests/src/test/resources/cte.yamsql
  yaml-tests/src/test/resources/showcasing-tests.metrics.binpb
  yaml-tests/src/test/resources/showcasing-tests.metrics.yaml
  yaml-tests/src/test/resources/showcasing-tests.yamsql
  yaml-tests/yaml-tests.gradle
Labels: enhancement

#3452 Allow yaml-test load template from json to add dependencies
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/CommandUtil.java
  yaml-tests/src/main/resources/standard_tests_metadata.json
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/proto/standard_tests.proto
  yaml-tests/src/test/proto/test_student.proto
  yaml-tests/src/test/resources/disabled-planner-rewrites/standard-tests-metadata.yamsql
  yaml-tests/src/test/resources/disabled-planner-rewrites/standard-tests-proto.metrics.binpb
  yaml-tests/src/test/resources/disabled-planner-rewrites/standard-tests-proto.metrics.yaml
  yaml-tests/src/test/resources/disabled-planner-rewrites/standard-tests-proto.yamsql
  yaml-tests/src/test/resources/standard-tests-metadata.yamsql
  yaml-tests/src/test/resources/standard-tests-proto.metrics.binpb
  yaml-tests/src/test/resources/standard-tests-proto.metrics.yaml
  yaml-tests/src/test/resources/standard-tests-proto.yamsql
Labels: testing improvement

#3484 Remove FieldDescription in Struct/ArrayMetadata in favour of DataType
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/ArrayMetaData.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/FieldDescription.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalArrayBuilder.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalArrayMetaData.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalStructBuilder.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/RelationalStructMetaData.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/SqlTypeNamesSupport.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/StructMetaData.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/StructResultSetMetaData.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/metadata/DataType.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/EmbeddedRelationalArray.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/EmbeddedRelationalStruct.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/RowArray.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/RowStruct.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/SqlTypeSupport.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/CatalogMetaData.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/EmbeddedRelationalConnection.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/MessageTuple.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/RecordStoreIndex.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/RecordTypeTable.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/catalog/RecordLayerStoreCatalog.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/catalog/RecordLayerStoreSchemaTemplateCatalog.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/ddl/RecordLayerCatalogQueryFactory.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/metadata/DataTypeUtils.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/AstNormalizer.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/LiteralsUtils.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/MutablePlanGenerationContext.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/QueryPlan.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/visitors/ExpressionVisitor.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/autotest/datagen/PrimitiveFieldGenerator.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/autotest/datagen/SchemaGenerator.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/autotest/datagen/StructFieldGenerator.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/memory/InMemorySchemaTemplateCatalog.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/memory/InMemoryTable.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/InsertTest.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/IteratorResultSetTest.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/RecordLayerResultSetTest.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/RowStructTest.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/TableWithEnumTest.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/TransactionBoundDatabaseWithEnumTest.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/PreparedStatementTests.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/QueryParserTests.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/StandardQueryTests.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/storage/BackingLocatableResolverStoreTest.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/utils/DdlPermutationGenerator.java
  fdb-relational-core/src/testFixtures/java/com/apple/foundationdb/relational/utils/RelationalStructAssert.java
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/RelationalArrayFacade.java
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/RelationalResultSetFacade.java
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/RelationalResultSetMetaDataFacade.java
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/RelationalStructFacade.java
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/TypeConversion.java
  fdb-relational-grpc/src/main/proto/grpc/relational/jdbc/v1/column.proto
  fdb-relational-grpc/src/main/proto/grpc/relational/jdbc/v1/jdbc.proto
  fdb-relational-grpc/src/test/java/com/apple/foundationdb/relational/jdbc/MockResultSetMetadata.java
  fdb-relational-grpc/src/test/java/com/apple/foundationdb/relational/jdbc/ProtobufConversionTest.java
  fdb-relational-grpc/src/test/java/com/apple/foundationdb/relational/jdbc/RelationalStructFacadeTest.java
  fdb-relational-grpc/src/test/java/com/apple/foundationdb/relational/jdbc/ResultSetContinuationTest.java
  fdb-relational-grpc/src/test/java/com/apple/foundationdb/relational/jdbc/TestUtils.java
  fdb-relational-jdbc/src/main/java/com/apple/foundationdb/relational/jdbc/ParameterHelper.java
  fdb-relational-server/src/main/java/com/apple/foundationdb/relational/server/FRL.java
Labels: enhancement

#3490 Add support for NULL type fields in ExecuteInsert
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/RecordTypeTable.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/SimpleDirectAccessInsertionTests.java
Labels: relational, bug fix

#3499 Omit portions of stack trace that are just junit in test summary
  gradle/testing.gradle
Labels: build improvement

#3506 `NULL` handling fixes in plan generator
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/RelOpValue.java
  fdb-record-layer-core/src/main/proto/record_query_plan.proto
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/Literals.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/query/MutablePlanGenerationContext.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/LogAppenderRule.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/LiteralsTests.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/cache/ConstraintValidityTests.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/query/cache/RelationalPlanCacheTests.java
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/null-extraction-tests.metrics.binpb
  yaml-tests/src/test/resources/null-extraction-tests.metrics.yaml
  yaml-tests/src/test/resources/null-extraction-tests.yamsql
Labels: bug fix
