Repository FoundationDB/fdb-record-layer, pull requests merged in 2025-09, with the labels that each got.

#3568 Upload coverage from nightly builds
  .github/workflows/nightly.yml
  .github/workflows/teamscale_upload.yml
  actions/teamscale-upload/action.yml
Labels: build improvement

#3579 Fix the indentation in the teamscale upload action.
  actions/teamscale-upload/action.yml
Labels: build improvement

#3557 Make YAML tests (and SQL more generally) able to encrypt records at rest
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordContext.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/RecordContextNotActiveException.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/Options.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/exceptions/ErrorCode.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/options/CollectionContract.java
  fdb-relational-api/src/test/java/com/apple/foundationdb/relational/api/OptionsTest.java
  fdb-relational-api/src/testFixtures/java/com/apple/foundationdb/relational/utils/OptionsTestHelper.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/api/EmbeddedRelationalDriver.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/AbstractDatabase.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/EmbeddedRelationalConnection.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/RecordLayerConfig.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/RecordLayerDatabase.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/catalog/TransactionBoundDatabase.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/ddl/RecordLayerCreateSchemaConstantAction.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/ddl/RecordLayerSetStoreStateConstantAction.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/storage/StoreConfig.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/util/ExceptionUtil.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/ContinuationTest.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/storage/BackingLocatableResolverStoreTest.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/recordlayer/util/ExceptionUtilTest.java
  fdb-relational-core/src/test/java/com/apple/foundationdb/relational/utils/Ddl.java
  fdb-relational-grpc/fdb-relational-grpc.gradle
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/TypeConversion.java
  fdb-relational-grpc/src/main/proto/grpc/relational/jdbc/v1/jdbc.proto
  fdb-relational-grpc/src/test/java/com/apple/foundationdb/relational/jdbc/ProtobufConversionTest.java
  fdb-relational-jdbc/src/main/java/com/apple/foundationdb/relational/jdbc/JDBCRelationalConnection.java
  fdb-relational-jdbc/src/main/java/com/apple/foundationdb/relational/jdbc/JDBCRelationalDriver.java
  fdb-relational-jdbc/src/main/java/com/apple/foundationdb/relational/jdbc/JDBCRelationalStatement.java
  fdb-relational-server/src/main/java/com/apple/foundationdb/relational/server/FRL.java
  fdb-relational-server/src/main/java/com/apple/foundationdb/relational/server/jdbc/v1/JDBCService.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/EmbeddedSimpleYamlConnection.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/SimpleYamlConnection.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/connectionfactory/EmbeddedYamlConnectionFactory.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/connectionfactory/MultiServerConnectionFactory.java
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/case-sensitivity.yamsql
  yaml-tests/src/test/resources/encrypted.p12
  yaml-tests/src/test/resources/encrypted.yamsql
Labels: enhancement, relational

#3530 Online Indexer: replace the synchronized runner with a heartbeat
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/logging/LogMessageKeys.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBStoreTimer.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingByIndex.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingCommon.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingSubspaces.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexOperationBaseBuilder.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexOperationConfig.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexScrubber.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexer.java
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexing/IndexingHeartbeat.java
  fdb-record-layer-core/src/main/proto/index_build.proto
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerBuildIndexTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerIndexFromIndexTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMultiTargetTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerMutualTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerSimpleTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexingHeartbeatTest.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/indexing/IndexingHeartbeatLowLevelTest.java
  gradle.properties
Labels: enhancement

#3618 Add a connection option to control compression
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/Options.java
  fdb-relational-api/src/main/java/com/apple/foundationdb/relational/api/options/TypeContract.java
  fdb-relational-api/src/testFixtures/java/com/apple/foundationdb/relational/utils/OptionsTestHelper.java
  fdb-relational-core/src/main/java/com/apple/foundationdb/relational/recordlayer/storage/StoreConfig.java
  fdb-relational-grpc/src/main/java/com/apple/foundationdb/relational/jdbc/TypeConversion.java
  fdb-relational-grpc/src/main/proto/grpc/relational/jdbc/v1/jdbc.proto
  yaml-tests/src/test/java/YamlIntegrationTests.java
  yaml-tests/src/test/resources/encrypted.yamsql
  yaml-tests/src/test/resources/serialization-keys.p12
  yaml-tests/src/test/resources/serialization-options.yamsql
Labels: testing improvement

#3620 Create tool to automate reviews of metrics files
  .github/workflows/metrics_analysis.yml
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/GitMetricsFileFinder.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/MetricsDiffAnalyzer.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/MetricsInfo.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/MetricsStatistics.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/YamlExecutionContext.java
  yaml-tests/src/main/java/com/apple/foundationdb/relational/yamltests/command/queryconfigs/CheckExplainConfig.java
  yaml-tests/src/test/java/com/apple/foundationdb/relational/yamltests/MetricsDiffAnalyzerTest.java
  yaml-tests/src/test/java/com/apple/foundationdb/relational/yamltests/MetricsDiffIntegrationTest.java
  yaml-tests/src/test/java/com/apple/foundationdb/relational/yamltests/MetricsStatisticsTest.java
  yaml-tests/src/test/resources/metrics-diff/metrics-diff-test-base.metrics.yaml
  yaml-tests/src/test/resources/metrics-diff/metrics-diff-test-head.metrics.yaml
  yaml-tests/src/test/resources/metrics-diff/metrics-outlier-test-base.metrics.yaml
  yaml-tests/src/test/resources/metrics-diff/metrics-outlier-test-head.metrics.yaml
  yaml-tests/src/test/resources/metrics-diff/test-base.metrics.yaml
  yaml-tests/src/test/resources/metrics-diff/test-head.metrics.yaml
  yaml-tests/src/test/resources/metrics-diff/test-new-queries.metrics.yaml
  yaml-tests/yaml-tests.gradle
Labels: testing improvement

#3625 improve memo-performance
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Reference.java
Labels: performance

#3628 Utilize testFixtures for `fdb-extensions`
  fdb-extensions/fdb-extensions.gradle
  fdb-extensions/src/testFixtures/java/com/apple/foundationdb/test/MultipleTransactions.java
  fdb-extensions/src/testFixtures/java/com/apple/foundationdb/test/TestClassSubspaceExtension.java
  fdb-extensions/src/testFixtures/java/com/apple/foundationdb/test/TestDatabaseExtension.java
  fdb-extensions/src/testFixtures/java/com/apple/foundationdb/test/TestExecutors.java
  fdb-extensions/src/testFixtures/java/com/apple/foundationdb/test/TestMdcExtension.java
  fdb-extensions/src/testFixtures/java/com/apple/foundationdb/test/TestSubspaceExtension.java
  fdb-extensions/src/testFixtures/java/com/apple/test/BooleanArgumentsProvider.java
  fdb-extensions/src/testFixtures/java/com/apple/test/BooleanSource.java
  fdb-extensions/src/testFixtures/java/com/apple/test/ParameterizedTestUtils.java
  fdb-extensions/src/testFixtures/java/com/apple/test/ParameterizedTestUtilsTest.java
  fdb-extensions/src/testFixtures/java/com/apple/test/RandomSeedProvider.java
  fdb-extensions/src/testFixtures/java/com/apple/test/RandomSeedSource.java
  fdb-extensions/src/testFixtures/java/com/apple/test/RandomizedTestUtils.java
  fdb-extensions/src/testFixtures/java/com/apple/test/SuperSlow.java
  fdb-extensions/src/testFixtures/java/com/apple/test/Tags.java
  fdb-extensions/src/testFixtures/java/com/apple/test/TestConfigurationUtils.java
  fdb-record-layer-core/fdb-record-layer-core.gradle
  fdb-record-layer-icu/fdb-record-layer-icu.gradle
  fdb-record-layer-lucene/fdb-record-layer-lucene.gradle
  fdb-record-layer-spatial/fdb-record-layer-spatial.gradle
Labels: testing improvement, build improvement

#3630 Use reference name "pull/PR_NUMBER/head" to get PR head reference
  .github/workflows/metrics_analysis.yml
Labels: build improvement

#3642 Allow TransformedRecordSerializerJCE.Builder to be reused
  fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/common/TransformedRecordSerializerJCE.java
  fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/common/TransformedRecordSerializerTest.java
Labels: bug fix
